### ISSUE TITLE
Ampersand (&) symbol causes error

### ISSUE THREAD

**Issue by guillaumegarcia13** [syntax-tree/xast-util-from-xml#1]
### Subject of the issue

When the XML contains and ampersand symbol (&), the following errror occurs:
```
C:\<Project path>\node_modules\xast-util-from-xml\index.js:340
    throw new Message(reason, now(), 'xast-util-from-xml:' + id)
    ^
[3:15: Invalid character in entity name] {
  reason: 'Invalid character in entity name',
  line: 3,
  column: 15,
  location: {
    start: { line: 3, column: 15, offset: 25 },
    end: { line: null, column: null }
  },
  source: 'xast-util-from-xml',
  ruleId: 'sax'
}
```

### Your environment

*   **OS**:  Windows 10 version 20H2
*   **Packages**: xast-util-from-xml 1.0.1 (latest to date)
*   **Env**:  node v12.21.0, npm 6.13.14

### Steps to reproduce

You can clone the MCVE 🎉 at: https://github.com/guillaumegarcia13/mcve-xast-util-from-xml-issue

### Expected behavior

Ampersand symbol should be processed as (mere) text

### Actual behavior

An error occurs when parsing

**Comment by ChristianMurphy** [comment]
Ampersand is a reserved character in XML.
From the spec: https://www.w3.org/TR/xml/#syntax

> The ampersand character (&) and the left angle bracket (<) MUST NOT appear in their literal form

The solution is also noted in the spec:

>  If they are needed elsewhere, they MUST be escaped using either numeric character references or the strings " \&amp; " and " \&lt; " respectively.

**Comment by guillaumegarcia13** [comment]
Thanks.
In the context I am, i found this useful:
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/895c88e8bd875488a62966680a3d9d8eb2bcd9ea/ask-sdk-core/lib/util/SsmlUtils.ts
